name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install fish
        run: sudo apt-get install -y fish

      - name: Test backward_shell_word
        run: tests/test_backward_shell_word.fish

      - name: Test forward_shell_word
        run: tests/test_forward_shell_word.fish
